window.PADBS_THEME = {
  id: "ferreteria",
  brand: {
    name: "Ferretería Digital Experience",
    icon: "🔩",
  },
  contactHref: "mailto:padbsconsulting@gmail.com?subject=Ferreteria%20Digital%20Experience%20-%207-Day%20Launch",
  access: {
    passwordHash: "3d878fb7c8c503a3a46dbc8dc2e565c7eb62f877daff9a17a2812f2a987da936",
  },
  pages: [
    { id: "executive", href: "index.html", icon: "📊" },
    { id: "inventory", href: "inventory.html", icon: "📦" },
    { id: "quotes", href: "quotes.html", icon: "🧾" },
    { id: "credit", href: "credit.html", icon: "🤝" },
    { id: "suppliers", href: "suppliers.html", icon: "🚚" },
    { id: "dispatch", href: "dispatch.html", icon: "🏬" },
    { id: "launch", href: "launch.html", icon: "🚀" },
  ],
  journey: ["executive", "inventory", "quotes", "credit", "suppliers", "dispatch", "launch"],
  actionIcons: {
    inventory: ["📦", "🔁", "🏗️"],
    quotes: ["🧾", "💬", "✅"],
    credit: ["🤝", "⚠️", "📈"],
    suppliers: ["🚚", "📋", "⏱️"],
    dispatch: ["🏬", "🛻", "📍"],
  },
  i18n: {
    es: {
      meta: {
        executive: { title: "Panorama ejecutivo", description: "Ferretería Digital Experience: vista premium para centralizar inventario, cotizaciones, crédito, compras y despacho." },
        inventory: { title: "Inventario inteligente", description: "Inventario, rotación, productos críticos y reposición sugerida para ferretería." },
        quotes: { title: "Cotización a venta", description: "Flujo comercial para convertir cotizaciones de materiales en ventas y despacho." },
        credit: { title: "Clientes y crédito", description: "Visibilidad de clientes frecuentes, crédito comercial y riesgo operativo." },
        suppliers: { title: "Proveedores y compras", description: "Planeación de compras y proveedores para una ferretería con control centralizado." },
        dispatch: { title: "Despacho y sucursales", description: "Coordinación de despacho, entregas y sucursales con visión ejecutiva." },
        launch: { title: "PADBS 7-Day Launch", description: "Ruta consultiva para modernizar una ferretería sin convertirla en un ERP pesado." },
      },
      nav: {
        modules: "Recorrido",
        executive: "Panorama del negocio",
        inventory: "Inventario y rotación",
        quotes: "Cotización a venta",
        credit: "Clientes y crédito",
        suppliers: "Compras y suplidores",
        dispatch: "Despacho y sucursales",
        launch: "7-Day Launch",
      },
      brand: {
        tagline: "Control operativo",
        demoEnv: "Vista ejecutiva",
        mockData: "Datos ficticios para conversación comercial",
      },
      common: {
        liveDemo: "Vista en vivo",
        toggleMenu: "Abrir menú",
        demoCommercial: "Demo consultivo",
        journey: {
          step: "Paso",
          of: "de",
          nextLabel: "Siguiente conversación",
          actionsTitle: "Decisiones que el negocio podría tomar mañana",
          actionsSubtitle: "Acciones comerciales y operativas sin caer en pantallas administrativas",
        },
        time: "Tiempo",
        event: "Evento",
        detail: "Detalle",
        product: "Producto",
        branch: "Sucursal",
        qty: "Cant.",
        status: "Estado",
        rank: "#",
        category: "Categoría",
        sold: "Vendidos",
        margin: "Margen",
        stock: "Stock",
        coverage: "días de cobertura",
        monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul"],
      },
      executive: {
        title: "Panorama del negocio",
        subtitle: "Una ferretería con mostrador activo, crédito, compras y despacho en una sola lectura",
        question: "¿Qué necesita ver el dueño antes de decidir?",
        bannerTitle: "De Mónica informal a control profesional, sin sentirlo como un ERP pesado",
        bannerText: "Esta demo muestra cómo una ferretería puede ordenar inventario, cotizaciones, clientes a crédito, suplidores y despacho en una experiencia clara para dueños y encargados.",
        bannerCta: "Ver señales de inventario",
        salesTrend: { title: "Ventas y cotizaciones", subtitle: "Lectura consolidada de enero a julio 2026" },
        operatingMix: { title: "Mix operativo del mes", subtitle: "Dónde se concentra la atención del equipo" },
        branchPerf: { title: "Rendimiento por sucursal", subtitle: "Ventas del mes, RD$" },
        insights: { title: "Señales del día", subtitle: "Alertas ejecutivas para decidir sin buscar reportes" },
        activity: { title: "Actividad reciente", subtitle: "Lo que la operación estaría dejando visible" },
        charts: { sales: "Ventas cotizadas y cerradas", branchSales: "Ventas del mes" },
        kpis: {
          salesMtd: { label: "Ventas del mes", subtext: "mostrador + entregas" },
          quotesOpen: { label: "Cotizaciones abiertas", subtext: "con seguimiento pendiente" },
          creditExposure: { label: "Crédito por cobrar", subtext: "clientes frecuentes" },
          stockHealth: { label: "Salud de inventario", subtext: "referencias críticas controladas" },
        },
        insightItems: {
          cement: { title: "Materiales de construcción en alta rotación", text: "Cemento, varilla y PVC concentran la presión de reposición de esta semana." },
          quoteFollowup: { title: "Cotizaciones listas para cerrar", text: "Ocho propuestas de contratistas superan RD$ 420K y requieren seguimiento hoy." },
          credit: { title: "Crédito visible antes de vender", text: "Tres clientes frecuentes están cerca del límite aprobado; el mostrador lo vería antes de facturar." },
          dispatch: { title: "Despacho coordinado por sucursal", text: "La ruta Norte puede agrupar entregas pesadas y bajar viajes duplicados." },
        },
        access: {},
      },
      inventory: {
        title: "Inventario y rotación",
        subtitle: "Saber qué se mueve, qué falta y dónde conviene reponer",
        question: "¿Qué productos no pueden faltar esta semana?",
        stockByCat: { title: "Stock por categoría", subtitle: "Unidades disponibles en sucursales y almacén" },
        turnover: { title: "Rotación por categoría", subtitle: "Índice de movimiento, últimos 90 días" },
        alerts: { title: "Productos que requieren acción", subtitle: "Referencias críticas antes de perder ventas" },
        branches: { title: "Cobertura por sucursal", subtitle: "Valor y días de inventario disponible" },
        topSkus: { title: "Alta rotación", subtitle: "Productos que sostienen el flujo del mostrador" },
        charts: { stock: "Unidades en stock", turnover: "Rotación (x)" },
        kpis: {
          activeSkus: { label: "Referencias activas", subtext: "catálogo comercial controlado" },
          stockValue: { label: "Valor en inventario", subtext: "incluye materiales pesados" },
          criticalItems: { label: "Críticos visibles", subtext: "reposición sugerida" },
          fillRate: { label: "Disponibilidad", subtext: "pedidos completados" },
        },
        actions: [
          { title: "Reponer antes del pico", desc: "Cemento y varilla tienen menos de 9 días de cobertura en la sucursal principal." },
          { title: "Mover stock entre sucursales", desc: "Pintura exterior está sobrada en Autopista y corta en Centro." },
          { title: "Proteger productos de obra", desc: "Materiales de construcción deben verse por volumen, margen y despacho disponible." },
        ],
      },
      quotes: {
        title: "Cotización a venta",
        subtitle: "Convertir presupuestos de obra en ventas claras y seguimiento útil",
        question: "¿Qué cotizaciones merecen seguimiento hoy?",
        primary: { title: "Embudo comercial", subtitle: "Cotizaciones por etapa, valor estimado" },
        secondary: { title: "Señales comerciales", subtitle: "Dónde el equipo puede cerrar mejor" },
        table: { title: "Cotizaciones prioritarias", subtitle: "Ficticias, orientadas a conversación comercial" },
        coordination: { title: "Flujo de mostrador", subtitle: "De solicitud a despacho sin convertirlo en burocracia" },
        kpis: {
          openValue: { label: "Valor abierto", subtext: "cotizaciones vigentes" },
          conversion: { label: "Conversión a venta", subtext: "últimos 30 días" },
          avgClose: { label: "Tiempo de cierre", subtext: "desde solicitud" },
          pendingFollowup: { label: "Seguimientos", subtext: "pendientes para hoy" },
        },
        insightItems: {
          contractors: { title: "Contratistas compran por continuidad", text: "La propuesta debe mostrar disponibilidad, crédito y entrega, no solo precio." },
          whatsapp: { title: "WhatsApp necesita trazabilidad", text: "La conversación puede iniciar por mensaje, pero el negocio necesita ver estado y valor." },
          bundles: { title: "Kits elevan el ticket", text: "Agrupar cemento, arena, varilla y herramientas evita cotizaciones incompletas." },
        },
        actions: [
          { title: "Prioriza por valor y fecha", desc: "Las cotizaciones grandes con despacho cercano deben subir al tablero del encargado." },
          { title: "Acompaña la venta consultiva", desc: "El vendedor ve disponibilidad, crédito y sugerencias sin abrir módulos técnicos." },
          { title: "Cierra con entrega clara", desc: "La cotización debe aterrizar en disponibilidad real y ruta posible." },
        ],
      },
      credit: {
        title: "Clientes y crédito",
        subtitle: "Frecuentes, maestros constructores y empresas con visibilidad antes de vender",
        question: "¿A quién conviene venderle a crédito con confianza?",
        primary: { title: "Exposición de crédito", subtitle: "Distribución por tipo de cliente" },
        secondary: { title: "Alertas comerciales", subtitle: "Riesgo y oportunidad en la misma lectura" },
        table: { title: "Clientes frecuentes", subtitle: "Ficticios, con límites y señales de comportamiento" },
        coordination: { title: "Salud de cartera", subtitle: "Lectura simple para mostrador y administración" },
        kpis: {
          frequentCustomers: { label: "Clientes frecuentes", subtext: "con historial comercial" },
          receivable: { label: "Por cobrar", subtext: "crédito autorizado" },
          overdue: { label: "Vencido controlado", subtext: "más de 30 días" },
          repeatRate: { label: "Recompra", subtext: "clientes activos 90 días" },
        },
        insightItems: {
          limit: { title: "Límite visible en el mostrador", text: "El vendedor no tiene que improvisar si un cliente ya está cerca del cupo." },
          loyalty: { title: "Frecuencia vale más que descuento", text: "Los maestros que compran semanalmente merecen seguimiento, no solo crédito." },
          collections: { title: "Cobro con contexto", text: "La administración ve promesas de pago junto a historial de compras." },
        },
        actions: [
          { title: "Vende con límites claros", desc: "El crédito acompaña la venta sin frenar al cliente bueno ni exponer la caja." },
          { title: "Activa cobros preventivos", desc: "Alertas suaves antes del vencimiento evitan conversaciones incómodas." },
          { title: "Segmenta clientes frecuentes", desc: "Constructor, maestro, empresa y hogar no deben recibir la misma atención." },
        ],
      },
      suppliers: {
        title: "Compras y suplidores",
        subtitle: "Planear compras según rotación, cobertura y tiempos reales de entrega",
        question: "¿Qué conviene comprar antes de que falte?",
        primary: { title: "Compras sugeridas", subtitle: "Valor por familia de producto" },
        secondary: { title: "Lecturas de suplidores", subtitle: "Riesgo de entrega y oportunidad de negociación" },
        table: { title: "Plan de compra", subtitle: "Ficticio, basado en rotación y cobertura" },
        coordination: { title: "Cumplimiento de suplidores", subtitle: "La compra no termina cuando se emite la orden" },
        kpis: {
          purchasePlan: { label: "Plan sugerido", subtext: "próximos 14 días" },
          suppliersActive: { label: "Suplidores activos", subtext: "con compras recientes" },
          leadTime: { label: "Entrega promedio", subtext: "familias críticas" },
          savings: { label: "Ahorro potencial", subtext: "por consolidar órdenes" },
        },
        insightItems: {
          cementSupplier: { title: "Cemento requiere anticipo", text: "El proveedor ficticio Construmax tarda 4 días si la orden sale después del jueves." },
          pvc: { title: "PVC puede consolidarse", text: "Un solo pedido para Centro y Norte baja flete y evita compras pequeñas." },
          price: { title: "Precios con señales", text: "El sistema muestra variaciones relevantes sin convertir la demo en compras técnicas." },
        },
        actions: [
          { title: "Compra por cobertura", desc: "La reposición parte de días disponibles, no de intuición." },
          { title: "Consolida órdenes", desc: "Agrupar familias reduce flete y mejora negociación." },
          { title: "Vigila entregas críticas", desc: "El dueño ve qué proveedor puede afectar ventas esta semana." },
        ],
      },
      dispatch: {
        title: "Despacho y sucursales",
        subtitle: "Coordinar mostrador, almacén, rutas y entregas sin perder control",
        question: "¿Cómo evitar prometer entregas que la operación no puede cumplir?",
        primary: { title: "Carga de despacho", subtitle: "Entregas por estado operativo" },
        secondary: { title: "Coordinación diaria", subtitle: "Señales para almacén, caja y sucursales" },
        table: { title: "Despachos de hoy", subtitle: "Ficticios, orientados a visibilidad ejecutiva" },
        coordination: { title: "Capacidad por zona", subtitle: "Entrega, retiro y transferencia entre sucursales" },
        kpis: {
          scheduled: { label: "Despachos agendados", subtext: "hoy" },
          onTime: { label: "A tiempo", subtext: "últimos 7 días" },
          branchTransfers: { label: "Transferencias", subtext: "entre sucursales" },
          counterWait: { label: "Espera mostrador", subtext: "promedio estimado" },
        },
        insightItems: {
          heavy: { title: "Material pesado necesita ruta", text: "Varilla, cemento y block deben prometerse con capacidad real de camión." },
          branch: { title: "Sucursal no es isla", text: "Centro puede vender con stock de Norte si el despacho queda claro." },
          cash: { title: "Caja y almacén conectados", text: "La salida del material se valida sin depender de llamadas internas." },
        },
        actions: [
          { title: "Promete con capacidad real", desc: "Cada venta ve si se entrega, se retira o se transfiere." },
          { title: "Agrupa rutas", desc: "Entregas por zona bajan viajes y mejoran cumplimiento." },
          { title: "Da control al encargado", desc: "El dueño ve cuellos de botella antes de que el cliente llame." },
        ],
      },
      launch: {
        title: "PADBS 7-Day Launch",
        subtitle: "Una ruta concreta para empezar sin sobredimensionar la operación",
        question: "¿Cómo se transforma esta visión en una primera semana de implementación?",
        kpis: {
          days: { label: "Días de lanzamiento", subtext: "primer alcance visible" },
          priorities: { label: "Prioridades iniciales", subtext: "inventario, cotización, crédito" },
          dataSources: { label: "Fuentes a ordenar", subtext: "Mónica, Excel, WhatsApp" },
          ownerView: { label: "Vista ejecutiva", subtext: "lista para conversación semanal" },
        },
        impact: {
          kicker: "Lo que la demo hace vendible",
          title: "Tres decisiones para iniciar con impacto",
          subtitle: "La modernización empieza por claridad operativa, no por reemplazar todo de golpe.",
        },
        roadmap: {
          kicker: "Ruta de implementación",
          title: "De conversación a primera versión en 7 días",
          subtitle: "PADBS define alcance, ordena datos ficticios o reales de prueba y entrega una experiencia navegable para decidir el siguiente paso.",
        },
        roi: {
          kicker: "Conversación de retorno",
          title: "Preguntas que ayudan al dueño a pensar el valor",
          subtitle: "No son promesas; son escenarios para dimensionar el costo de operar con información dispersa.",
        },
        cta: {
          kicker: "Siguiente paso",
          title: "Diseñemos la primera semana de la Ferretería Digital Experience",
          subtitle: "Una sesión para elegir alcance, datos iniciales, prioridades comerciales y la vista ejecutiva que debe quedar lista.",
          button: "Solicitar conversación PADBS",
          note: "Demo con datos ficticios. La implementación real se define con alcance, fuentes y prioridades del negocio.",
        },
      },
      access: {
        welcome: {
          brand: "PADBS Consulting",
          title: "Ferretería Digital Experience",
          subtitle: "Una conversación premium sobre control operativo, ventas y crecimiento",
          version: "Industry Theme v1.0",
          enter: "Explorar la visión",
        },
        modal: {
          title: "Acceso privado",
          subtitle: "Ingresa la clave para continuar",
          placeholder: "Clave de acceso",
          submit: "Continuar",
          error: "Clave incorrecta. Intenta nuevamente.",
          securityNote: "Sesión privada para revisión comercial. No contiene datos reales de clientes.",
          timeoutTitle: "Sesión pausada",
          timeoutSubtitle: "Por seguridad, confirma el acceso para continuar",
        },
      },
    },
    en: {
      meta: {
        executive: { title: "Executive overview", description: "Hardware Store Digital Experience: premium PADBS demo for inventory, quotes, credit, purchasing, and dispatch." },
        inventory: { title: "Inventory intelligence", description: "Inventory, turnover, critical products, and suggested replenishment for a hardware store." },
        quotes: { title: "Quote to sale", description: "Commercial journey to turn construction-material quotes into sales and dispatch." },
        credit: { title: "Customers and credit", description: "Visibility into frequent customers, trade credit, and operating risk." },
        suppliers: { title: "Suppliers and purchasing", description: "Purchase planning and supplier visibility for a hardware store with centralized control." },
        dispatch: { title: "Dispatch and branches", description: "Dispatch, delivery, and branch coordination through an executive view." },
        launch: { title: "PADBS 7-Day Launch", description: "Consulting path to modernize a hardware store without turning it into a heavy ERP." },
      },
      nav: {
        modules: "Journey",
        executive: "Business overview",
        inventory: "Inventory and turnover",
        quotes: "Quote to sale",
        credit: "Customers and credit",
        suppliers: "Purchasing and suppliers",
        dispatch: "Dispatch and branches",
        launch: "7-Day Launch",
      },
      brand: {
        tagline: "Operational control",
        demoEnv: "Executive view",
        mockData: "Fictional data for commercial conversation",
      },
      common: {
        liveDemo: "Live view",
        toggleMenu: "Open menu",
        demoCommercial: "Consultative demo",
        journey: {
          step: "Step",
          of: "of",
          nextLabel: "Next conversation",
          actionsTitle: "Decisions the business could make tomorrow",
          actionsSubtitle: "Commercial and operational actions without falling into admin screens",
        },
        time: "Time",
        event: "Event",
        detail: "Detail",
        product: "Product",
        branch: "Branch",
        qty: "Qty.",
        status: "Status",
        rank: "#",
        category: "Category",
        sold: "Sold",
        margin: "Margin",
        stock: "Stock",
        coverage: "days of coverage",
        monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
      },
      executive: {
        title: "Business overview",
        subtitle: "Counter sales, credit, purchasing, and dispatch in one clear reading",
        question: "What does the owner need to see before deciding?",
        bannerTitle: "From informal Mónica use to professional control, without feeling like a heavy ERP",
        bannerText: "This demo helps a hardware store imagine inventory, quotes, credit customers, suppliers, and dispatch in one clear experience for owners and managers.",
        bannerCta: "See inventory signals",
        salesTrend: { title: "Sales and quotes", subtitle: "Consolidated reading from January to July 2026" },
        operatingMix: { title: "Operating mix this month", subtitle: "Where the team is spending attention" },
        branchPerf: { title: "Branch performance", subtitle: "Monthly sales, RD$" },
        insights: { title: "Daily signals", subtitle: "Executive alerts without hunting reports" },
        activity: { title: "Recent activity", subtitle: "What the operation would make visible" },
        charts: { sales: "Quoted and closed sales", branchSales: "Monthly sales" },
        kpis: {
          salesMtd: { label: "Monthly sales", subtext: "counter + deliveries" },
          quotesOpen: { label: "Open quotes", subtext: "pending follow-up" },
          creditExposure: { label: "Receivables", subtext: "frequent customers" },
          stockHealth: { label: "Inventory health", subtext: "critical items controlled" },
        },
        insightItems: {
          cement: { title: "Construction materials are moving fast", text: "Cement, rebar, and PVC are putting the most pressure on replenishment this week." },
          quoteFollowup: { title: "Quotes ready to close", text: "Eight contractor proposals exceed RD$ 420K and require follow-up today." },
          credit: { title: "Credit visible before selling", text: "Three frequent customers are close to their approved limit; the counter would see it before invoicing." },
          dispatch: { title: "Dispatch coordinated by branch", text: "The North route can group heavy deliveries and reduce duplicate trips." },
        },
      },
      inventory: {
        title: "Inventory and turnover",
        subtitle: "Know what moves, what is missing, and where to replenish",
        question: "Which products cannot run out this week?",
        stockByCat: { title: "Stock by category", subtitle: "Available units across branches and warehouse" },
        turnover: { title: "Turnover by category", subtitle: "Movement index, last 90 days" },
        alerts: { title: "Products requiring action", subtitle: "Critical items before lost sales" },
        branches: { title: "Coverage by branch", subtitle: "Inventory value and available days" },
        topSkus: { title: "High-rotation products", subtitle: "Products that keep the counter moving" },
        charts: { stock: "Units in stock", turnover: "Turnover (x)" },
        kpis: {
          activeSkus: { label: "Active SKUs", subtext: "controlled commercial catalog" },
          stockValue: { label: "Inventory value", subtext: "includes heavy materials" },
          criticalItems: { label: "Visible criticals", subtext: "suggested replenishment" },
          fillRate: { label: "Availability", subtext: "orders completed" },
        },
        actions: [
          { title: "Replenish before the peak", desc: "Cement and rebar have less than 9 days of coverage in the main branch." },
          { title: "Move stock across branches", desc: "Exterior paint is high in Autopista and short in Centro." },
          { title: "Protect construction products", desc: "Construction materials need to be seen by volume, margin, and dispatch availability." },
        ],
      },
      quotes: {
        title: "Quote to sale",
        subtitle: "Turn construction quotes into clear sales and useful follow-up",
        question: "Which quotes deserve follow-up today?",
        primary: { title: "Commercial funnel", subtitle: "Quotes by stage, estimated value" },
        secondary: { title: "Commercial signals", subtitle: "Where the team can close better" },
        table: { title: "Priority quotes", subtitle: "Fictional, designed for commercial conversation" },
        coordination: { title: "Counter flow", subtitle: "From request to dispatch without bureaucracy" },
        kpis: {
          openValue: { label: "Open value", subtext: "active quotes" },
          conversion: { label: "Conversion to sale", subtext: "last 30 days" },
          avgClose: { label: "Time to close", subtext: "from request" },
          pendingFollowup: { label: "Follow-ups", subtext: "pending today" },
        },
        insightItems: {
          contractors: { title: "Contractors buy continuity", text: "The proposal needs to show availability, credit, and delivery, not only price." },
          whatsapp: { title: "WhatsApp needs traceability", text: "The conversation can start by message, but the business needs status and value visibility." },
          bundles: { title: "Kits lift ticket size", text: "Grouping cement, sand, rebar, and tools prevents incomplete quotes." },
        },
        actions: [
          { title: "Prioritize by value and date", desc: "Large quotes with near dispatch dates should rise to the manager view." },
          { title: "Support consultative selling", desc: "The seller sees availability, credit, and suggestions without technical modules." },
          { title: "Close with clear delivery", desc: "The quote lands on real availability and a possible route." },
        ],
      },
      credit: {
        title: "Customers and credit",
        subtitle: "Frequent customers, builders, and companies visible before selling",
        question: "Who can be sold to on credit with confidence?",
        primary: { title: "Credit exposure", subtitle: "Distribution by customer type" },
        secondary: { title: "Commercial alerts", subtitle: "Risk and opportunity in the same reading" },
        table: { title: "Frequent customers", subtitle: "Fictional, with limits and behavioral signals" },
        coordination: { title: "Portfolio health", subtitle: "A simple reading for counter and administration" },
        kpis: {
          frequentCustomers: { label: "Frequent customers", subtext: "with purchase history" },
          receivable: { label: "Receivable", subtext: "authorized credit" },
          overdue: { label: "Controlled overdue", subtext: "over 30 days" },
          repeatRate: { label: "Repeat purchase", subtext: "active customers 90 days" },
        },
        insightItems: {
          limit: { title: "Limit visible at the counter", text: "The seller does not have to improvise when a customer is close to the credit cap." },
          loyalty: { title: "Frequency beats discounts", text: "Builders who buy weekly deserve follow-up, not just credit." },
          collections: { title: "Collections with context", text: "Administration sees payment promises next to purchase history." },
        },
        actions: [
          { title: "Sell with clear limits", desc: "Credit supports the sale without blocking good customers or exposing cash." },
          { title: "Activate preventive collections", desc: "Soft alerts before due dates avoid uncomfortable conversations." },
          { title: "Segment frequent customers", desc: "Contractor, builder, company, and home buyer should not receive the same attention." },
        ],
      },
      suppliers: {
        title: "Purchasing and suppliers",
        subtitle: "Plan purchases by turnover, coverage, and real delivery times",
        question: "What should be purchased before it runs out?",
        primary: { title: "Suggested purchasing", subtitle: "Value by product family" },
        secondary: { title: "Supplier readings", subtitle: "Delivery risk and negotiation opportunity" },
        table: { title: "Purchase plan", subtitle: "Fictional, based on turnover and coverage" },
        coordination: { title: "Supplier compliance", subtitle: "Purchasing does not end when the order is issued" },
        kpis: {
          purchasePlan: { label: "Suggested plan", subtext: "next 14 days" },
          suppliersActive: { label: "Active suppliers", subtext: "with recent purchases" },
          leadTime: { label: "Average delivery", subtext: "critical families" },
          savings: { label: "Potential savings", subtext: "by consolidating orders" },
        },
        insightItems: {
          cementSupplier: { title: "Cement requires lead time", text: "Fictional supplier Construmax takes 4 days if the order leaves after Thursday." },
          pvc: { title: "PVC can be consolidated", text: "One order for Centro and Norte lowers freight and avoids small purchases." },
          price: { title: "Pricing with signals", text: "The system shows relevant variations without turning the demo into technical purchasing." },
        },
        actions: [
          { title: "Buy by coverage", desc: "Replenishment starts from days available, not intuition." },
          { title: "Consolidate orders", desc: "Grouping families reduces freight and improves negotiation." },
          { title: "Watch critical deliveries", desc: "The owner sees which supplier can affect sales this week." },
        ],
      },
      dispatch: {
        title: "Dispatch and branches",
        subtitle: "Coordinate counter, warehouse, routes, and deliveries without losing control",
        question: "How do you avoid promising deliveries the operation cannot fulfill?",
        primary: { title: "Dispatch load", subtitle: "Deliveries by operating status" },
        secondary: { title: "Daily coordination", subtitle: "Signals for warehouse, cash register, and branches" },
        table: { title: "Today's dispatches", subtitle: "Fictional, designed for executive visibility" },
        coordination: { title: "Capacity by zone", subtitle: "Delivery, pickup, and branch transfer" },
        kpis: {
          scheduled: { label: "Scheduled dispatches", subtext: "today" },
          onTime: { label: "On time", subtext: "last 7 days" },
          branchTransfers: { label: "Transfers", subtext: "between branches" },
          counterWait: { label: "Counter wait", subtext: "estimated average" },
        },
        insightItems: {
          heavy: { title: "Heavy material needs routing", text: "Rebar, cement, and blocks should be promised with real truck capacity." },
          branch: { title: "A branch is not an island", text: "Centro can sell with North stock if dispatch is clear." },
          cash: { title: "Cash register and warehouse connected", text: "Material release is validated without internal calls." },
        },
        actions: [
          { title: "Promise with real capacity", desc: "Every sale sees delivery, pickup, or transfer feasibility." },
          { title: "Group routes", desc: "Zone-based deliveries reduce trips and improve fulfillment." },
          { title: "Give managers control", desc: "The owner sees bottlenecks before the customer calls." },
        ],
      },
      launch: {
        title: "PADBS 7-Day Launch",
        subtitle: "A concrete path to start without overbuilding the operation",
        question: "How does this vision become a first implementation week?",
        kpis: {
          days: { label: "Launch days", subtext: "first visible scope" },
          priorities: { label: "Initial priorities", subtext: "inventory, quotes, credit" },
          dataSources: { label: "Sources to organize", subtext: "Mónica, Excel, WhatsApp" },
          ownerView: { label: "Executive view", subtext: "ready for weekly conversation" },
        },
        impact: {
          kicker: "What the demo makes sellable",
          title: "Three decisions to start with impact",
          subtitle: "Modernization starts with operating clarity, not replacing everything at once.",
        },
        roadmap: {
          kicker: "Implementation path",
          title: "From conversation to first version in 7 days",
          subtitle: "PADBS defines scope, organizes approved sample extracts, and delivers a navigable experience to decide the next step.",
        },
        roi: {
          kicker: "Return conversation",
          title: "Questions that help the owner think about value",
          subtitle: "These are not promises; they are scenarios to size the cost of operating with scattered information.",
        },
        cta: {
          kicker: "Next step",
          title: "Let's design the first week of the Hardware Store Digital Experience",
          subtitle: "One session to choose scope, initial data, commercial priorities, and the executive view that must be ready.",
          button: "Request PADBS conversation",
          note: "Demo with fictional data. The real implementation is defined by scope, sources, and business priorities.",
        },
      },
      access: {
        welcome: {
          brand: "PADBS Consulting",
          title: "Hardware Store Digital Experience",
          subtitle: "A premium conversation about operating control, sales, and growth",
          version: "Industry Theme v1.0",
          enter: "Explore the vision",
        },
        modal: {
          title: "Private access",
          subtitle: "Enter the key to continue",
          placeholder: "Access key",
          submit: "Continue",
          error: "Incorrect key. Please try again.",
          securityNote: "Private commercial review. No real customer data is included.",
          timeoutTitle: "Session paused",
          timeoutSubtitle: "For security, confirm access to continue",
        },
      },
    },
  },
  data: {
    company: {
      branches: ["Centro", "Autopista", "Norte", "Almacén"],
    },
    executive: {
      kpis: [
        { id: "salesMtd", value: "RD$ 6.34M", trend: "+14.8%", direction: "up" },
        { id: "quotesOpen", value: "RD$ 1.18M", trend: "24 activas", direction: "neutral" },
        { id: "creditExposure", value: "RD$ 2.06M", trend: "-6.2%", direction: "up" },
        { id: "stockHealth", value: "91%", trend: "+4pp", direction: "up" },
      ],
      salesTrend: [3820000, 4150000, 4380000, 4760000, 5120000, 5880000, 6340000],
      branchPerformance: [2380000, 1840000, 1320000, 800000],
      operatingMix: {
        labels: {
          es: ["Ventas mostrador", "Cotizaciones", "Crédito", "Despacho", "Compras"],
          en: ["Counter sales", "Quotes", "Credit", "Dispatch", "Purchasing"],
        },
        values: [36, 22, 16, 14, 12],
      },
      insights: [
        { id: "cement", icon: "🏗️", type: "gold" },
        { id: "quoteFollowup", icon: "🧾", type: "blue" },
        { id: "credit", icon: "🤝", type: "coral" },
        { id: "dispatch", icon: "🛻", type: "green" },
      ],
      activity: [
        { time: { es: "Hace 14 min", en: "14 min ago" }, event: { es: "Cotización actualizada", en: "Quote updated" }, detail: { es: "Residencial Palmas, materiales de terminación", en: "Residencial Palmas, finishing materials" } },
        { time: { es: "Hace 31 min", en: "31 min ago" }, event: { es: "Alerta de cobertura", en: "Coverage alert" }, detail: { es: "Cemento gris por debajo de 8 días en Centro", en: "Gray cement below 8 days in Centro" } },
        { time: { es: "Hace 1 h", en: "1h ago" }, event: { es: "Pago aplicado", en: "Payment applied" }, detail: { es: "Constructora Alba redujo balance de crédito", en: "Constructora Alba reduced credit balance" } },
        { time: { es: "Hace 2 h", en: "2h ago" }, event: { es: "Ruta consolidada", en: "Route consolidated" }, detail: { es: "Tres entregas pesadas agrupadas hacia Norte", en: "Three heavy deliveries grouped to North" } },
      ],
    },
    inventory: {
      kpis: [
        { id: "activeSkus", value: "3,420", trend: "+180", direction: "up" },
        { id: "stockValue", value: "RD$ 18.7M", trend: "+3.4%", direction: "neutral" },
        { id: "criticalItems", value: "18", trend: "-7", direction: "up" },
        { id: "fillRate", value: "93.5%", trend: "+2.1pp", direction: "up" },
      ],
      categories: {
        labels: {
          es: ["Construcción", "Plomería", "Eléctrico", "Pintura", "Herramientas", "Tornillería"],
          en: ["Construction", "Plumbing", "Electrical", "Paint", "Tools", "Fasteners"],
        },
        stock: [1420, 980, 760, 1120, 640, 5200],
        turnover: [6.6, 5.1, 4.2, 4.8, 3.6, 7.2],
      },
      alerts: [
        { sku: "CEM-GR-42", product: "Cemento gris 42.5kg", branch: "Centro", qty: 86, status: "critical", label: { es: "Crítico", en: "Critical" } },
        { sku: "VAR-3-8", product: "Varilla 3/8 x 20'", branch: "Norte", qty: 42, status: "critical", label: { es: "Crítico", en: "Critical" } },
        { sku: "PVC-1-2", product: "Tubo PVC presión 1/2", branch: "Autopista", qty: 118, status: "warning", label: { es: "Atención", en: "Watch" } },
        { sku: "PIN-EXT-BL", product: "Pintura exterior blanca", branch: "Centro", qty: 24, status: "warning", label: { es: "Atención", en: "Watch" } },
      ],
      branches: [
        { name: "Centro", units: 4380, value: "RD$ 6.2M", coverage: 22 },
        { name: "Autopista", units: 3920, value: "RD$ 5.1M", coverage: 34 },
        { name: "Norte", units: 2860, value: "RD$ 3.8M", coverage: 25 },
        { name: "Almacén", units: 6120, value: "RD$ 3.6M", coverage: 42 },
      ],
      topSkus: [
        { rank: 1, product: "Cemento gris 42.5kg", category: { es: "Construcción", en: "Construction" }, sold: 1260, margin: "18%", stock: 420 },
        { rank: 2, product: "Varilla 3/8 x 20'", category: { es: "Construcción", en: "Construction" }, sold: 840, margin: "21%", stock: 210 },
        { rank: 3, product: "Tubo PVC presión 1/2", category: { es: "Plomería", en: "Plumbing" }, sold: 620, margin: "32%", stock: 380 },
        { rank: 4, product: "Breaker 20A", category: { es: "Eléctrico", en: "Electrical" }, sold: 410, margin: "35%", stock: 190 },
        { rank: 5, product: "Tornillo drywall 1 1/4", category: { es: "Tornillería", en: "Fasteners" }, sold: 3800, margin: "44%", stock: 9200 },
      ],
    },
    quotes: {
      kpis: [
        { id: "openValue", value: "RD$ 1.18M", trend: "+9.2%", direction: "up" },
        { id: "conversion", value: "42%", trend: "+5pp", direction: "up" },
        { id: "avgClose", value: "2.8 días", trend: "-0.7", direction: "up" },
        { id: "pendingFollowup", value: "8", trend: "hoy", direction: "neutral" },
      ],
      chart: {
        type: "bar",
        labels: { es: ["Solicitada", "Enviada", "Negociación", "Aprobada"], en: ["Requested", "Sent", "Negotiation", "Approved"] },
        label: { es: "Valor RD$", en: "Value RD$" },
        values: [320000, 410000, 280000, 170000],
      },
      insights: [{ id: "contractors", icon: "🏗️", type: "gold" }, { id: "whatsapp", icon: "💬", type: "blue" }, { id: "bundles", icon: "🧰", type: "green" }],
      table: {
        headers: { es: ["Cliente", "Necesidad", "Valor", "Próximo paso"], en: ["Customer", "Need", "Value", "Next step"] },
        rows: [
          [{ es: "Constructora Alba", en: "Constructora Alba" }, { es: "Terminación apartamentos", en: "Apartment finishing" }, "RD$ 248K", { es: "Confirmar entrega", en: "Confirm delivery" }],
          [{ es: "Maestro Joel", en: "Builder Joel" }, { es: "Material gris", en: "Gray materials" }, "RD$ 112K", { es: "Validar crédito", en: "Validate credit" }],
          [{ es: "Residencial Palmas", en: "Residencial Palmas" }, { es: "Pintura y eléctrico", en: "Paint and electrical" }, "RD$ 186K", { es: "Seguimiento hoy", en: "Follow up today" }],
        ],
      },
      progress: [
        { label: { es: "Solicitud recibida", en: "Request received" }, value: "100%", percent: 100 },
        { label: { es: "Disponibilidad validada", en: "Availability validated" }, value: "78%", percent: 78, accent: true },
        { label: { es: "Entrega prometida con ruta", en: "Delivery promised with route" }, value: "64%", percent: 64 },
      ],
    },
    credit: {
      kpis: [
        { id: "frequentCustomers", value: "486", trend: "+11%", direction: "up" },
        { id: "receivable", value: "RD$ 2.06M", trend: "-6.2%", direction: "up" },
        { id: "overdue", value: "RD$ 318K", trend: "-12%", direction: "up" },
        { id: "repeatRate", value: "69%", trend: "+4pp", direction: "up" },
      ],
      chart: {
        type: "doughnut",
        labels: { es: ["Constructoras", "Maestros", "Empresas", "Hogar frecuente"], en: ["Construction firms", "Builders", "Companies", "Frequent home buyers"] },
        label: { es: "Exposición", en: "Exposure" },
        values: [42, 28, 18, 12],
      },
      insights: [{ id: "limit", icon: "⚠️", type: "coral" }, { id: "loyalty", icon: "🤝", type: "gold" }, { id: "collections", icon: "📌", type: "blue" }],
      table: {
        headers: { es: ["Cliente", "Tipo", "Balance", "Señal"], en: ["Customer", "Type", "Balance", "Signal"] },
        rows: [
          ["Constructora Alba", { es: "Empresa", en: "Company" }, "RD$ 420K", { es: "Pago parcial aplicado", en: "Partial payment applied" }],
          ["Maestro Joel", { es: "Maestro constructor", en: "Builder" }, "RD$ 86K", { es: "Cerca del límite", en: "Near limit" }],
          ["Hotel Costa Norte", { es: "Empresa", en: "Company" }, "RD$ 214K", { es: "Compra mensual estable", en: "Stable monthly buyer" }],
        ],
      },
      progress: [
        { label: { es: "Cartera al día", en: "Current portfolio" }, value: "72%", percent: 72, accent: true },
        { label: { es: "Promesas de pago visibles", en: "Payment promises visible" }, value: "84%", percent: 84 },
        { label: { es: "Clientes con límite aprobado", en: "Customers with approved limit" }, value: "58%", percent: 58 },
      ],
    },
    suppliers: {
      kpis: [
        { id: "purchasePlan", value: "RD$ 3.4M", trend: "14 días", direction: "neutral" },
        { id: "suppliersActive", value: "38", trend: "+4", direction: "up" },
        { id: "leadTime", value: "3.6 días", trend: "-0.5", direction: "up" },
        { id: "savings", value: "RD$ 146K", trend: "potencial", direction: "up" },
      ],
      chart: {
        type: "bar",
        labels: { es: ["Construcción", "Plomería", "Eléctrico", "Pintura"], en: ["Construction", "Plumbing", "Electrical", "Paint"] },
        label: { es: "Compra sugerida", en: "Suggested purchase" },
        values: [1450000, 620000, 540000, 790000],
      },
      insights: [{ id: "cementSupplier", icon: "🚚", type: "gold" }, { id: "pvc", icon: "📦", type: "green" }, { id: "price", icon: "📈", type: "blue" }],
      table: {
        headers: { es: ["Suplidor", "Familia", "Orden sugerida", "Riesgo"], en: ["Supplier", "Family", "Suggested order", "Risk"] },
        rows: [
          ["Construmax", { es: "Cemento y varilla", en: "Cement and rebar" }, "RD$ 1.2M", { es: "Entrega jueves", en: "Thursday delivery" }],
          ["Tubos Caribe", "PVC", "RD$ 420K", { es: "Consolidar flete", en: "Consolidate freight" }],
          ["Pinturas Atlas", { es: "Pintura exterior", en: "Exterior paint" }, "RD$ 380K", { es: "Precio sube 3%", en: "Price up 3%" }],
        ],
      },
      progress: [
        { label: { es: "Órdenes a tiempo", en: "Orders on time" }, value: "88%", percent: 88 },
        { label: { es: "Compras consolidadas", en: "Consolidated purchases" }, value: "61%", percent: 61, accent: true },
        { label: { es: "Suplidores con precio actualizado", en: "Suppliers with updated prices" }, value: "74%", percent: 74 },
      ],
    },
    dispatch: {
      kpis: [
        { id: "scheduled", value: "32", trend: "hoy", direction: "neutral" },
        { id: "onTime", value: "91%", trend: "+6pp", direction: "up" },
        { id: "branchTransfers", value: "11", trend: "-3", direction: "up" },
        { id: "counterWait", value: "7 min", trend: "-2", direction: "up" },
      ],
      chart: {
        type: "doughnut",
        labels: { es: ["Listo", "En ruta", "Pendiente almacén", "Reprogramado"], en: ["Ready", "On route", "Warehouse pending", "Rescheduled"] },
        label: { es: "Despachos", en: "Dispatches" },
        values: [12, 9, 8, 3],
      },
      insights: [{ id: "heavy", icon: "🛻", type: "coral" }, { id: "branch", icon: "🏬", type: "gold" }, { id: "cash", icon: "💳", type: "blue" }],
      table: {
        headers: { es: ["Cliente", "Zona", "Carga", "Estado"], en: ["Customer", "Zone", "Load", "Status"] },
        rows: [
          ["Constructora Alba", "Norte", { es: "Cemento + varilla", en: "Cement + rebar" }, { es: "En ruta", en: "On route" }],
          ["Residencial Palmas", "Centro", { es: "Pintura + eléctrico", en: "Paint + electrical" }, { es: "Listo almacén", en: "Warehouse ready" }],
          ["Maestro Joel", "Autopista", { es: "Material gris", en: "Gray materials" }, { es: "Retiro en tienda", en: "Store pickup" }],
        ],
      },
      progress: [
        { label: { es: "Zona Norte", en: "North zone" }, value: "82%", percent: 82, accent: true },
        { label: { es: "Zona Centro", en: "Central zone" }, value: "68%", percent: 68 },
        { label: { es: "Retiro en sucursal", en: "Branch pickup" }, value: "76%", percent: 76 },
      ],
    },
    launch: {
      kpis: [
        { id: "days", value: "7", trend: "PADBS", direction: "neutral" },
        { id: "priorities", value: "3", trend: "inicio", direction: "up" },
        { id: "dataSources", value: "3", trend: "ordenar", direction: "neutral" },
        { id: "ownerView", value: "1", trend: "central", direction: "up" },
      ],
      impact: [
        { title: { es: "Controlar lo que más rota", en: "Control what moves fastest" }, text: { es: "Inventario crítico y alta rotación primero: cemento, varilla, PVC, pintura y eléctrico.", en: "Critical and high-turnover inventory first: cement, rebar, PVC, paint, and electrical." }, signal: { es: "Inventario · Caja · Compras", en: "Inventory · Counter · Purchasing" } },
        { title: { es: "Cerrar cotizaciones con seguimiento", en: "Close quotes with follow-up" }, text: { es: "El dueño ve valor abierto, estado y próximo paso antes de que el cliente compre en otro lugar.", en: "The owner sees open value, status, and next step before the customer buys elsewhere." }, signal: { es: "Cotizaciones · WhatsApp · Despacho", en: "Quotes · WhatsApp · Dispatch" } },
        { title: { es: "Vender a crédito con claridad", en: "Sell on credit with clarity" }, text: { es: "El mostrador conoce límite, balance y señales antes de comprometer más capital.", en: "The counter knows limit, balance, and signals before committing more capital." }, signal: { es: "Clientes frecuentes · Crédito", en: "Frequent customers · Credit" } },
      ],
      roadmap: [
        { tag: { es: "Día 1", en: "Day 1" }, title: { es: "Alinear prioridades", en: "Align priorities" }, desc: { es: "Elegir los indicadores y conversaciones que más importan al dueño.", en: "Choose the indicators and conversations that matter most to the owner." }, duration: { es: "Sesión ejecutiva", en: "Executive session" } },
        { tag: { es: "Días 2-3", en: "Days 2-3" }, title: { es: "Ordenar fuentes", en: "Organize sources" }, desc: { es: "Mapear Mónica, Excel, WhatsApp y reportes actuales sin prometer migración total.", en: "Map Mónica, Excel, WhatsApp, and current reports without promising a full migration." }, duration: { es: "Mapa inicial de fuentes", en: "Initial source map" } },
        { tag: { es: "Días 4-5", en: "Days 4-5" }, title: { es: "Construir vista demo-real", en: "Build demo-real view" }, desc: { es: "Adaptar tablero, recorridos, datos y mensajes al negocio de la ferretería.", en: "Adapt dashboard, journeys, data, and messaging to the hardware store." }, duration: { es: "Experiencia navegable", en: "Navigable experience" } },
        { tag: { es: "Días 6-7", en: "Days 6-7" }, title: { es: "Validar y decidir próximo paso", en: "Validate and decide next step" }, desc: { es: "Revisar con dueño y encargados qué se implementa primero.", en: "Review with owner and managers what gets implemented first." }, duration: { es: "Plan de implementación", en: "Implementation plan" } },
      ],
      roi: [
        { prompt: { es: "¿Cuánto cuesta quedarse sin cemento o varilla un sábado?", en: "What does running out of cement or rebar on Saturday cost?" }, range: { es: "Menos ventas perdidas · mejor compra anticipada", en: "Fewer lost sales · better early purchasing" }, note: { es: "Basado en señales de cobertura y alta rotación.", en: "Based on coverage and high-turnover signals." } },
        { prompt: { es: "¿Cuántas cotizaciones se enfrían por falta de seguimiento?", en: "How many quotes go cold due to lack of follow-up?" }, range: { es: "Más cierres · menos oportunidades invisibles", en: "More closes · fewer invisible opportunities" }, note: { es: "Basado en valor abierto y próximo paso.", en: "Based on open value and next step." } },
        { prompt: { es: "¿Qué pasa si el crédito se ve antes de facturar?", en: "What happens if credit is visible before invoicing?" }, range: { es: "Caja más protegida · ventas con confianza", en: "More protected cash · confident selling" }, note: { es: "Basado en límites, balances y clientes frecuentes.", en: "Based on limits, balances, and frequent customers." } },
      ],
    },
  },
};
